engines:
  csslint:
    enabled: true
    checks:
      important:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- test/
- tests/
- "server/migrations.js"
- "imports/config/GlobalSettings.js"
- "server/migrate_v*.js"
