sudo: required
language: node_js
node_js:
  - "stable"
addons:
  code_climate:
    repo_token: 7cba96725def6b43bf4df46cdbf57029a9a665607cd5d627cc5c4114755b4db0
before_install:
  - curl https://install.meteor.com | /bin/sh
  - npm install -g chimp
  - npm install -g babel-cli
before_script:
  - meteor npm run test:end2end:server&
  - sleep 30
script:
  - npm run test:unit:coverage
after_script:
  - codeclimate-test-reporter < coverage/lcov.info