sudo: required
language: node_js

addons:
  artifacts:
    debug: true
    paths:
    - $(ls ./tests/snapshots/* | tr "\n" ":")

cache:
  directories:
    - node_modules
    - .meteor
    - ~/.meteor
    - $(npm config get prefix)/bin/chimp

node_js:
  - "stable"

before_install:
  - mkdir ./tests/snapshots
  - curl https://install.meteor.com | /bin/sh
  - npm install -g chimp@0.36.1

before_script:
  - meteor npm run test:end2end:server&
  - sleep 30

script: chimp --ddp=http://localhost:3100 --mocha --path=tests/end2end/ --browser=phantomjs --watch
