sudo: required
language: node_js

addons:
  artifacts:
    debug: true
    s3_region: "us-west-2" # defaults to "us-east-1"
    paths:
    - $(ls ./tests/snapshots/* | tr "\n" ":")

cache:
  directories:
    - node_modules
    - .meteor
    - ~/.meteor
    - $(npm config get prefix)/bin/chimp

node_js:
  - "stable"

before_install:
  - mkdir ./tests/snapshots
  - curl https://install.meteor.com | /bin/sh
  - npm install -g chimp@0.34.1

before_script:
  - meteor npm run test:end2end:server&
  - sleep 30

script: npm run test:ci
