sudo: required
language: node_js
node_js:
  - "stable"
before_install:
  - curl https://install.meteor.com | /bin/sh
  - npm install -g chimp
  - npm install -g babel-cli
  - npm install -g codeclimate-test-reporter
before_script:
  - meteor npm run test:end2end:server&
  - sleep 30
script: npm run test:ci