version: '3.1'

services:
  4minitz:
    image: 4minitz/4minitz:dev
 
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - 4minitz

networks:
  4minitz: