version: '3.1'

services:
  4minitz:
    build:
      context: ./.deploy
      dockerfile: $PWD/.docker/Dockerfile
      args:
        - VCS_REF=12345abcde
        - VERSION=dev-docker

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - 4minitz

networks:
  4minitz:
