@startuml

MeetingSeries "1" --> "*" MeetingMinutes
MeetingMinutes "1" --> "*" Topic
Topic <|-- ActionItem
Topic <|-- Decision
Topic <|-- Information


class MeetingSeries {
    string project
    string name
}

class MeetingMinutes {
    Date date
    string[] participants
    string text
}
@enduml
