@startuml

Meeting "1" --> "*" Minutes
Minutes "1" --> "*" Topic
Topic <|-- ActionItem
Topic <|-- Decision
Topic <|-- Information

note right of Meeting: aka MeetingType ;-)

class Meeting {
    string project
    string name
}

class Minutes {
    Date date
    string[] participants
    string text
}
@enduml
