@startuml
!include style.puml

Topic "1" --> "*" TopicItem

TopicItem  <|-- Information
TopicItem  <|-- ActionItem

class Topic {
    subject
    start
    responsibles
    status
    isRecurring
}

abstract class TopicItem {
    subject
    createdAt
    tags: []
}

class Information {
}

class ActionItem {
    dueDate
    responsibles
    status
    priority
    details: []
}


' ************************ notes
note right of (Topic)
    This is an Agenda Topic
end note


@enduml