name: 4Minitz CI TestRunner
on: [push, pull_request]

jobs:
  MyTest:
    runs-on: ubuntu-latest

#    strategy:
#      matrix:
#        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '8.9.4'
    - run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - run: sudo apt-get install gcc-4.8 -y --option Acquire::Retries=100 --option Acquire::http::Timeout="300"
    - run: curl https://install.meteor.com | /bin/sh
      env:
        CXX: g++-4.8
    - run: npm install -g chimp@0.51.1
      env:
        CXX: g++-4.8
    - run: npm install
      env:
        CXX: g++-4.8
    - run: npm run test:unit
