name: 4Minitz CI TestRunner
on: [push, pull_request]

jobs:
  UnitTests:
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '8.9.4'
    - run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - run: sudo apt-get install gcc-4.8 -y --option Acquire::Retries=100 --option Acquire::http::Timeout="300"
    - run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
    - run: curl https://install.meteor.com | /bin/sh
    - run: npm install -g chimp@0.51.1
    - run: npm install
    - run: npm run test:unit

  End2EndTests:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ":99.0"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '8.9.4'
      - run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - run: sudo apt-get install gcc-4.8 -y --option Acquire::Retries=100 --option Acquire::http::Timeout="300"
      - run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
      - run: curl https://install.meteor.com | /bin/sh
      - run: npm install -g chimp@0.51.1
      - run: npm install
      - run: sh -e /etc/init.d/xvfb start
      - run: sleep 3                             # give xvfb some time to start
      - run: npm run test:unit
