name: 4Minitz CI TestRunner
on: [push, pull_request]

jobs:
  UnitTestsAndI18n:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '8.9.4'
    - run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - run: sudo apt-get install gcc-4.8 -y --option Acquire::Retries=100 --option Acquire::http::Timeout="300"
    - run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
    - run: curl https://install.meteor.com | /bin/sh
    - run: pwd
    - run: meteor --version
    - run: npm install

    - run: npm run test:unit
    - run: npm run test:i18n


  End2EndTests:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: end2end   # evaluated by .babel.rc
      HEADLESS: 1         # evaluated by wdio.conf.js
    strategy:
      fail-fast: true   # When set to true, GitHub cancels all in-progress jobs if any matrix job fails. Default: true
      matrix:
        e2etest:
          - tests/e2e2/helloWorld-test.js
          - tests/e2e2/helloWDIO-test.js
          - tests/e2e2/hello4Minitz-test.js
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '8.9.4'

      - run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - run: sudo apt-get install gcc-4.8 -y --option Acquire::Retries=100 --option Acquire::http::Timeout="300"
      - run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
      - run: curl https://install.meteor.com | /bin/sh
      - run: pwd
      - run: meteor --version
      - run: npm install
      - uses: actions/setup-node@v1
        with:
          node-version: '12.16.2'
      - run: google-chrome --version
      - run: npm i chromedriver@^80.0.0

      - uses: actions/setup-node@v1
        with:
          node-version: '8.9.4'
      - run: ./tests/e2e2/run_e2e.sh ${{ matrix.e2etest }}

      - uses: actions/upload-artifact@v1
        with:
          name: E2E Screenshots
          path: tests/snapshots

