name: 4Minitz CI TestRunner
on: [push, pull_request]

jobs:
  UnitTestsAndI18n:
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '8.9.4'
    - run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - run: sudo apt-get install gcc-4.8 -y --option Acquire::Retries=100 --option Acquire::http::Timeout="300"
    - run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
    - run: curl https://install.meteor.com | /bin/sh
#    - run: npm install -g chimp@0.51.1
    - run: npm install

    - run: npm run test:unit
    - run: npm run test:i18n


  End2EndTests:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ":99.0"
    strategy:
      matrix:
        e2etest:
          - tests/e2e2/helloWorld-test.js
          - tests/e2e2/helloWDIO-test.js
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '8.9.4'
      - run: sudo apt-get install xvfb
      - run: xvfb-run :99.0 &
      - run: sleep 3                             # give xvfb some time to start
      - run: pwd

      - run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - run: sudo apt-get install gcc-4.8 -y --option Acquire::Retries=100 --option Acquire::http::Timeout="300"
      - run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
      - run: curl https://install.meteor.com | /bin/sh
      - run: meteor --version
      - run: npm install
      - run: google-chrome --version
      - uses: actions/setup-node@v1
        with:
          node-version: '12.16.2'
      - run: node --version
      - run: npm i chromedriver@^80.0.0
      - uses: actions/setup-node@v1
        with:
          node-version: '8.9.4'
      - run: ./tests/e2e2/run_e2e.sh ${{ matrix.e2etest }}
